name: Create Maven Release

on: workflow_dispatch

jobs:
  perform-release:
    runs-on: ubuntu-latest
    name: Perform Maven release
    steps:
    - uses: actions/checkout@v2
    - id: perform
      uses: mcarlett/release-explicit-version-action@v0.05
      with:
        devel-branch: $GITHUB_REF
        release-branch: master
    - run: "echo generated release: ${{ steps.perform.outputs.generated-tag }}"
      shell: bash
