name: Publish Maven Release

<<<<<<< HEAD
on:
  release:
    types: [created]
=======
on: [push, pull_request]
>>>>>>> 49388198da1904e8f6346dce9947d9528255110e

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Install package
<<<<<<< HEAD
        run: mvn clean install -U -B -DskipTests=true
      - name: Maven Verify
        run: mvn -B verify
      - name: Create custom Maven settings
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          servers: '[
            {
              "id":"jboss-releases-repository",
              "username":"${env.JBOSS_USERNAME}",
              "password":"${env.JBOSS_PASSWORD}"
            },
            {
              "id":"jboss-snapshots-repository",
              "username":"${env.JBOSS_USERNAME}",
              "password":"${env.JBOSS_PASSWORD}"
            }
          ]'
      - name: Maven Deploy
        run: mvn -X deploy -DskipTests
        env:
          JBOSS_USERNAME: ${{ secrets.JBOSS_USERNAME }}
          JBOSS_PASSWORD: ${{ secrets.JBOSS_PASSWORD }}
=======
        run: mvn install -U
>>>>>>> 49388198da1904e8f6346dce9947d9528255110e
