name: Publish Maven Release

on:
  release:
    types: [created]
jobs:
  publish:
    name: Publish artifact to repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
      - name: Install package
        run: mvn install -U -B -DskipTests=true
      - name: Maven Verify
        run: mvn -B verify
